server:
  port: 8000

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/student-db}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/cefomar-digital
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    convert:
      resourceId: cefomar-client
      principalAttribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html