server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student-db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

