server:
  port: 8000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fuji-vanilli/cefomar-web-repo-config.git

  datasource:
    url: jdbc:mysql://localhost:3306/student-db
    username: root
    password:

  jpa:
    hibernate:
      properties:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true



