server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student-db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/cefomar-digital
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    convert:
      resourceId: cefomar-client
      principalAttribute: preferred_name

