server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student-db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true



